// PARAMETROS (ARREGLOS) Estos se ingresan manualmente a mendida que se agregan mas catalogos o imagenes de prodctos  
// Nombre raiz de las fotos de los catalogos
const nombreCatalogos = [ "Andressa 2021", "Brigitte 2021","Maia 2020","Kaury 2021", "Bakhou 2019"];

// Arreglo de detalle de  productos (eventualmente habría que pasarlo a una base de datos y leerlo SQL o similar en  Python)
const listado = 
[   { "marca": "Andressa","foto": 1,"modelo": "","talleMin": "","talleMax": "","colores": [],"cantidad": 0 },
    { "marca": "Andressa","foto": 2,"modelo": "L5477","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rojo"],"cantidad": 0 },
    { "marca": "Andressa","foto": 3,"modelo": "L5495","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Nude", "Sofía"],"cantidad": 0 },
    { "marca": "Andressa","foto": 4,"modelo": "L5589","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Sofía", "Azul", "Frutilla", "Rojo", "Vino"],"cantidad": 0 },
    { "marca": "Andressa","foto": 5,"modelo": "L5607","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Nude", "Sofía"],"cantidad": 0},
    { "marca": "Andressa","foto": 6,"modelo": "L5508","talleMin": "85","talleMax": "100","colores": ["Blanco", "Crudo", "Negro", "Sofía", "Rojo"],"cantidad": 0 },
    { "marca": "Andressa","foto": 7,"modelo": "L5627","talleMin": "85","talleMax": "100","colores": ["Negro", "Rosa Perla", "Azul"],"cantidad": 0 },
    { "marca": "Andressa","foto": 8,"modelo": "L5651","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rojo"],"cantidad": 0 },
    { "marca": "Andressa","foto": 9,"modelo": "L5655","talleMin": "90","talleMax": "105","colores": ["Negro", "Nude", "Azul", "Vino"],"cantidad": 0 },
    { "marca": "Andressa","foto": 10,"modelo": "L5659","talleMin": "85","talleMax": "100","colores": ["Blanco", "Crudo", "Negro", "Sofía", "Rosa Perla", "Rojo"],"cantidad": 0 },
    { "marca": "Andressa","foto": 11,"modelo": "L5666","talleMin": "85","talleMax": "105","colores": ["Blanco", "Negro", "Rosa Perla", "Nude"],"cantidad": 0 },
    { "marca": "Andressa","foto": 12,"modelo": "L5667","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rosa Perla", "Aero"],"cantidad": 0 },
    { "marca": "Andressa","foto": 13,"modelo": "L5668","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro"],"cantidad": 0 },
    { "marca": "Andressa","foto": 14,"modelo": "L5668","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro"],"cantidad": 0 },
    { "marca": "Andressa","foto": 15,"modelo": "L5670","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Visión", "Azul", "Frutilla", "Rojo", "Vino", "Rosa Perla", "Nude", "Crudo"],"cantidad": 0 },
    { "marca": "Andressa","foto": 16,"modelo": "L5671","talleMin": "85","talleMax": "105","colores": ["Blanco", "Negro", "Visión"],"cantidad": 0 },
    { "marca": "Andressa","foto": 17,"modelo": "L5675","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro"],"cantidad": 0 },
    { "marca": "Andressa","foto": 18,"modelo": "L5683","talleMin": "85","talleMax": "100","colores": ["Animal Print", "Reptil Print", "Camel Print", "Rosa", "Flor Rosa/Negro"],"cantidad": 0 },
    { "marca": "Andressa","foto": 19,"modelo": "L5683","talleMin": "85","talleMax": "100","colores": ["Animal Print Rosa"],"cantidad": 0 },
    { "marca": "Andressa","foto": 20,"modelo": "L5687","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rubí", "Nude"],"cantidad": 0 },

    { "marca": "Brigitte","foto": 1,"modelo": "","talleMin": "","talleMax": "","colores": [],"cantidad": 0 },
    { "marca": "Brigitte","foto": 2,"modelo": "","talleMin": "","talleMax": "","colores": [],"cantidad": 0 },
    { "marca": "Brigitte","foto": 3,"modelo": "2130","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rojo", "Lemon", "Lila"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 4,"modelo": "2130","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rojo", "Lemon", "Lila"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 5,"modelo": "2130","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rojo", "Lemon", "Lila"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 6,"modelo": "1000","talleMin": "85","talleMax": "105","colores": ["Blanco", "Negro", "Rojo", "Francia", "Rosé"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 7,"modelo": "1000","talleMin": "85","talleMax": "105","colores": ["Blanco", "Negro", "Rojo", "Francia", "Rosé"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 8,"modelo": "1084","talleMin": "90","talleMax": "105","colores": ["Blanco", "Negro", "Flamingo", "Marino", "Lila"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 9,"modelo": "1084","talleMin": "90","talleMax": "105","colores": ["Blanco", "Negro", "Flamingo", "Marino", "Lila"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 10,"modelo": "2122","talleMin": "90","talleMax": "100","colores": ["Blanco", "Negro", "Fucsia"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 11,"modelo": "2122","talleMin": "90","talleMax": "100","colores": ["Blanco", "Negro", "Fucsia"],"cantidad": 0},
    { "marca": "Brigitte","foto": 12,"modelo": "1108","talleMin": "90","talleMax": "100","colores": ["Blanco", "Negro", "Francia", "Pink", "Rosé", "Oliva"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 13,"modelo": "1108","talleMin": "90","talleMax": "100","colores": ["Blanco", "Negro", "Francia", "Pink", "Rosé", "Oliva"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 14,"modelo": "2144","talleMin": "S","talleMax": "L","colores": ["Blanco", "Negro"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 15,"modelo": "2144","talleMin": "S","talleMax": "L","colores": ["Blanco", "Negro"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 17,"modelo": "2140","talleMin": "85","talleMax": "105","colores": ["Blanco", "Negro", "Pink", "Oliva"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 16,"modelo": "2140","talleMin": "85","talleMax": "105","colores": ["Blanco", "Negro", "Pink", "Oliva"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 18,"modelo": "442","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rojo", "Francia", "Menta"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 19,"modelo": "442","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rojo", "Francia", "Menta"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 20,"modelo": "1440","talleMin": "95","talleMax": "110","colores": ["Blanco", "Negro", "Rojo", "Rosé"],"cantidad": 0 },
    { "marca": "Brigitte","foto": 21,"modelo": "1440","talleMin": "95","talleMax": "110","colores": ["Blanco", "Negro", "Rojo", "Rosé"],"cantidad": 0 },

    { "marca": "Bakhou","foto": 1,"modelo": "","talleMin": "","talleMax": "","colores": [],"cantidad": 0 },
    { "marca": "Bakhou","foto": 2,"modelo": "2001","talleMin": "S","talleMax": "XL","colores": ["Azul Marino", "Gris Melange", "Negro", "Rojo"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 3,"modelo": "2001","talleMin": "S","talleMax": "XL","colores": ["Azul Marino", "Gris Melange", "Negro", "Rojo"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 4,"modelo": "2210","talleMin": "S","talleMax": "XXL","colores": ["Azul", "Negro", "Verde"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 5,"modelo": "2210","talleMin": "S","talleMax": "XXL","colores": ["Azul", "Negro", "Verde"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 6,"modelo": "2043","talleMin": "S","talleMax": "XXL","colores": ["Gris", "Verde"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 7,"modelo": "2043","talleMin": "S","talleMax": "XXL","colores": ["Gris", "Verde"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 8,"modelo": "2032","talleMin": "S","talleMax": "XXL","colores": ["Blanco", "Naranja", "Turquesa"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 9,"modelo": "2032","talleMin": "S","talleMax": "XXL","colores": ["Blanco", "Naranja", "Turquesa"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 10,"modelo": "2035","talleMin": "S","talleMax": "XL","colores": ["Blanco c/Negro", "Negro c/Rojo"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 11,"modelo": "2035","talleMin": "S","talleMax": "XL","colores": ["Blanco c/Negro", "Negro c/Rojo"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 12,"modelo": "2005","talleMin": "S","talleMax": "XXL","colores": ["Celeste","Coral", "Negro", "Verde Agua"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 13,"modelo": "2005","talleMin": "S","talleMax": "XXL","colores": ["Celeste","Coral", "Negro", "Verde Agua"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 14,"modelo": "2071","talleMin": "S","talleMax": "XL","colores": ["Azul Marino","Celeste", "Verde Agua", "Negro"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 15,"modelo": "2071","talleMin": "S","talleMax": "XL","colores": ["Azul Marino","Celeste", "Verde Agua", "Negro"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 16,"modelo": "2011","talleMin": "S","talleMax": "XL","colores": ["Azul Marino","Celeste", "Coral", "Negro"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 17,"modelo": "2011","talleMin": "S","talleMax": "XL","colores": ["Azul Marino","Celeste", "Coral", "Negro"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 18,"modelo": "2012","talleMin": "S","talleMax": "XL","colores": ["Rojo","Celeste", "Verde", "Violeta"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 19,"modelo": "2012","talleMin": "S","talleMax": "XL","colores": ["Rojo","Celeste", "Verde", "Violeta"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 20,"modelo": "2057","talleMin": "S","talleMax": "XL","colores": ["Rojo","Gris", "Turquesa", "Violeta"],"cantidad": 0 },
    { "marca": "Bakhou","foto": 21,"modelo": "2057","talleMin": "S","talleMax": "XL","colores": ["Rojo","Gris", "Turquesa", "Violeta"],"cantidad": 0 },

    { "marca": "Kaury","foto": 1,"modelo": "","talleMin": "","talleMax": "","colores": [],"cantidad": 0 },
    { "marca": "Kaury","foto": 2,"modelo": "8141","talleMin": "90","talleMax": "100","colores": ["Blanco", "Negro", "Rosa Vintage"],"cantidad": 0 },
    { "marca": "Kaury","foto": 3,"modelo": "8141","talleMin": "90","talleMax": "100","colores": ["Blanco", "Negro", "Rosa Vintage"],"cantidad": 0 },
    { "marca": "Kaury","foto": 4,"modelo": "8139","talleMin": "90","talleMax": "100","colores": ["Blanco", "Negro", "Rojo"],"cantidad": 0 },
    { "marca": "Kaury","foto": 5,"modelo": "8139","talleMin": "90","talleMax": "100","colores": ["Blanco", "Negro", "Rojo"],"cantidad": 0 },
    { "marca": "Kaury","foto": 6,"modelo": "8140","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rojo"],"cantidad": 0 },
    { "marca": "Kaury","foto": 7,"modelo": "8140","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rojo"],"cantidad": 0 },
    { "marca": "Kaury","foto": 8,"modelo": "8138","talleMin": "85","talleMax": "100","colores": ["Blanco", "Bordó", "Negro"],"cantidad": 0 },
    { "marca": "Kaury","foto": 9,"modelo": "8138","talleMin": "85","talleMax": "100","colores": ["Blanco", "Bordó", "Negro"],"cantidad": 0 },
    { "marca": "Kaury","foto": 10,"modelo": "8137","talleMin": "85","talleMax": "100","colores": ["Blanco", "Bordó", "Negro"],"cantidad": 0 },
    { "marca": "Kaury","foto": 11,"modelo": "8137","talleMin": "85","talleMax": "100","colores": ["Blanco", "Bordó", "Negro"],"cantidad": 0 },
    { "marca": "Kaury","foto": 12,"modelo": "7080","talleMin": "90","talleMax": "100","colores": ["Blanco", "Rojo", "Negro", "Azul Noche"],"cantidad": 0 },
    { "marca": "Kaury","foto": 13,"modelo": "8127","talleMin": "90","talleMax": "100","colores": ["Blanco", "Rojo", "Negro"],"cantidad": 0 },
    { "marca": "Kaury","foto": 14,"modelo": "8099","talleMin": "S","talleMax": "L","colores": ["Blanco", "Rojo", "Negro", "Rosa Vintage", "Verde Militar"],"cantidad": 0 },
    { "marca": "Kaury","foto": 15,"modelo": "8118","talleMin": "S","talleMax": "L","colores": ["Rojo", "Negro", "Azul Noche"],"cantidad": 0 },
    { "marca": "Kaury","foto": 16,"modelo": "","talleMin": "","talleMax": "","colores": [],"cantidad": 0 },
    { "marca": "Kaury","foto": 17,"modelo": "8092","talleMin": "90","talleMax": "100","colores": ["Celeste", "Negro", "Nude", "Rosa Vintage"],"cantidad": 0 },
    { "marca": "Kaury","foto": 18,"modelo": "8144","talleMin": "S","talleMax": "L","colores": ["Negro"],"cantidad": 0 },
    { "marca": "Kaury","foto": 19,"modelo": "8144","talleMin": "S","talleMax": "L","colores": ["Negro"],"cantidad": 0 },
    { "marca": "Kaury","foto": 20,"modelo": "8070","talleMin": "90","talleMax": "100","colores": ["Blanco", "Bodró", "Negro", "Verde Militar"],"cantidad": 0 },
    { "marca": "Kaury","foto": 21,"modelo": "8070","talleMin": "90","talleMax": "100","colores": ["Blanco", "Bodró", "Negro", "Verde Militar"],"cantidad": 0 },
 
    { "marca": "Maia","foto": 1,"modelo": "","talleMin": "","talleMax": "","colores": [],"cantidad": 0 },
    { "marca": "Maia","foto": 2,"modelo": "","talleMin": "","talleMax": "","colores": [],"cantidad": 0 },
    { "marca": "Maia","foto": 3,"modelo": "5090","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rojo", "Azul"],"cantidad": 0 },
    { "marca": "Maia","foto": 4,"modelo": "5090","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rojo", "Azul"],"cantidad": 0 },
    { "marca": "Maia","foto": 5,"modelo": "5090","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rojo", "Azul"],"cantidad": 0 },
    { "marca": "Maia","foto": 6,"modelo": "4360","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rojo", "Azul"],"cantidad": 0 },
    { "marca": "Maia","foto": 7,"modelo": "4360","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rojo", "Azul"],"cantidad": 0 },
    { "marca": "Maia","foto": 8,"modelo": "4350","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Hueso", "Azul"],"cantidad": 0 },
    { "marca": "Maia","foto": 9,"modelo": "4350","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Hueso", "Azul"],"cantidad": 0 },
    { "marca": "Maia","foto": 10,"modelo": "3700","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Mandarina", "Azul", "Rojo"],"cantidad": 0 },
    { "marca": "Maia","foto": 11,"modelo": "3700","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Mandarina", "Azul", "Rojo"],"cantidad": 0 },
    { "marca": "Maia","foto": 12,"modelo": "3500","talleMin": "85","talleMax": "100","colores": ["Blanco c/Azul",  "Mandarina/Hueso", "Azul c/Negro", "Rojo8Negro"],"cantidad": 0 },
    { "marca": "Maia","foto": 13,"modelo": "4160","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Nude", "Azul"],"cantidad": 0 },
    { "marca": "Maia","foto": 14,"modelo": "3780","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Mandarina"],"cantidad": 0 },
    { "marca": "Maia","foto": 15,"modelo": "3780","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Mandarina"],"cantidad": 0 },
    { "marca": "Maia","foto": 16,"modelo": "4150","talleMin": "85","talleMax": "100","colores": ["Azul", "Blanco", "Negro", "Mandarina"],"cantidad": 0 },
    { "marca": "Maia","foto": 17,"modelo": "4150","talleMin": "85","talleMax": "100","colores": ["Azul", "Blanco", "Negro", "Mandarina"],"cantidad": 0 },
    { "marca": "Maia","foto": 18,"modelo": "","talleMin": "","talleMax": "","colores": [],"cantidad": 0 },
    { "marca": "Maia","foto": 19,"modelo": "5060","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rosa"],"cantidad": 0 },
    { "marca": "Maia","foto": 20,"modelo": "5060","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rosa"],"cantidad": 0 },
    { "marca": "Maia","foto": 21,"modelo": "5060","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rosa"],"cantidad": 0 },
    { "marca": "Maia","foto": 22,"modelo": "6025","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rojo"],"cantidad": 0 },
    { "marca": "Maia","foto": 23,"modelo": "6025","talleMin": "85","talleMax": "100","colores": ["Blanco", "Negro", "Rojo"],"cantidad": 0 }


]   
 